apiVersion: v1
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc: {}


    processors:
      batch:

    exporters:
      logging:
        loglevel: debug
     

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
 

        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]

        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]




kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"otel-collector-config":"receivers:\n  otlp:\n    protocols:\n      grpc:\n        endpoint: ${env:MY_POD_IP}:4317\n      http:\n        endpoint: ${env:MY_POD_IP}:4318\nprocessors:\n  batch:\n  memory_limiter:\n    # 80% of maximum memory up to 2G\n    limit_mib: 1500\n    # 25% of limit up to 2G\n    spike_limit_mib: 512\n    check_interval: 5s\nextensions:\n  zpages: {}\nexporters:\n  otlp:\n    endpoint: \"http://someotlp.target.com:4317\" # Replace with a real endpoint.\n    tls:\n      insecure: true\nservice:\n  extensions: [zpages]\n  pipelines:\n    traces/1:\n      receivers: [otlp]\n      processors: [memory_limiter, batch]\n      exporters: [otlp]\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"opentelemetry","component":"otel-collector-conf"},"name":"otel-collector-conf","namespace":"aks"}}
  creationTimestamp: "2024-11-12T19:02:25Z"
  labels:
    app: opentelemetry
    component: otel-collector-conf
  name: otel-collector-conf
  namespace: aks
  resourceVersion: "77050375"
  uid: 07e9e7b8-1e04-4f76-a3ce-5421cd18f4c9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  replicas: 1
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.51.0
        ports: 
        - containerPort: 4317
        - containerPort: 4318
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /var/log
          name: varlog
          readOnly: true
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /etc/otelcol-contrib/config.yaml
          name: data
          subPath: otel-collector-config  # This must match the key in the ConfigMap
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: data
        configMap:
          name: otel-collector-conf  # This should match the name of the ConfigMap

